server:
  port: 10291
spring:
  application:
    name: product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.66:8848 #注意这个的discovery和bootstrap.yml的config!!!两个都要同时配置
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"